version: '3'
services:
  app:
    build: docker/app
    volumes:
      - ./backend:/go/src/app
    ports:
      - "63000:8080"
    environment:
      - "DSN=postgres://imguser:bTyRuxEU@database:5432/imageupload?sslmode=disable"
    links:
      - db:database

  db:
    image: postgres:10.1
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=imguser"
      - "POSTGRES_PASSWORD=bTyRuxEU"
      - "POSTGRES_DB=imageupload"

